version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5001:5001"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend
